config/routes.rb
Rails.application.routes.draw do
  get '/' => 'homes#top', as: "root"
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: "book"
  get 'books/:id/edit' => 'books#edit', as: "edit_book"
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div class="error_message">
    <h2>
      <%= @book.errors.count %> errors prohibited this book from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <div class="error_form">
    <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>
      <div class="field">
        <div class="field_with_error">
          <label for="book_title">Title</label>
        </div>
        <div class="field_with_error">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="field">
        <div class="field_with_error">
          <label for="book_body">Body</label>
        </div>
        <div class="field_with_error">
          <%= f.text_area :body %>
        </div>
      </div>
      <div class="action">
        <%= f.submit 'Update Book' %>
      </div>

    <% end %>
  </div>
  <%= link_to "Show", book_path %>
  |
  <%= link_to "Back", books_path %>
<% else %>
  <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>
    <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label for="book_body">Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="action">
      <%= f.submit 'Update Book' %>
    </div>
<% end %>
  <%= link_to "Show", book_path %>
  |
  <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <tr>
    <th class="title">Title</th>
    <th class="body">Body</th>
    <th colspan=3></th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td class="title"><%= book.title %></td>
      <td class="body"><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
  <% end %>
</table>
<h2 class>New book</h2>

<% if @book.errors.any? %>
  <div class="error_message">
    <h2>
      <%= @book.errors.count %> errors prohibited this book from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <div class="error_form">
    <%= form_with model: @book do |f| %>
      <div class="field">
        <div class="field_with_error">
          <label for="book_title">Title</label>
        </div>
        <div class="field_with_error">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="field">
        <div class="field_with_error">
          <label for="book_body">Body</label>
        </div>
        <div class="field_with_error">
          <%= f.text_area :body %>
        </div>
      </div>
      <div class="action">
        <%= f.submit 'Create Book' %>
      </div>
    <% end %>
  </div>
<% else %>
  <%= form_with model: @book do |f| %>
    <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label for="book_body">Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="action">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>
<% end %>

app/views/books/show.html.erb
<p>
  <span class="index">Title:</span>
  <%= @book.title %>
</p>

<p>
  <span class="index">Body:</span>
  <%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</P>
<P>印象を共有し交換することができます</p>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <p class="notice">
      <%= flash[:notice] %>
    <p>
    <%= yield %>
  </body>
</html>